run_id: robotwin_qwenoft
run_root_dir: checkpoints
seed: 42
wandb_entity: null
wandb_project: starVLA_Robotwin
is_debug: false

framework:
  name: QwenOFT
  qwenvl:
    base_vlm: /po2/heimrih/VLA-JEPA/model/Qwen3-VL-2B-Instruct
    attn_implementation: sdpa
    vl_hidden_dim: 2048
  action_model:
    action_model_type: MLP
    action_hidden_dim: 2048
    hidden_size: 1024
    add_pos_embed: true
    max_seq_len: 1024
    action_dim: 14
    state_dim: 14
    future_action_window_size: 49
    action_horizon: 50
    past_action_window_size: 0
    repeated_diffusion_steps: 8
    noise_beta_alpha: 1.5
    noise_beta_beta: 1.0
    noise_s: 0.999
    num_timestep_buckets: 1000
    num_inference_timesteps: 4
    num_target_vision_tokens: 32
    diffusion_model_cfg:
      dropout: 0.2
      final_dropout: true
      interleave_self_attention: true
      norm_type: ada_norm
      num_layers: 16
      output_dim: 2048
      positional_embeddings: null
  vj2_model:
    num_frames: 1

datasets:
  vla_data:
    dataset_py: lerobot_datasets
    include_state: false
    data_root_dir: /po2/heimrih/VLA-JEPA/dataset/RoboTwin-Randomized
    data_mix: robotwin_all_50
    action_type: abs_qpos
    action_mode: abs
    delete_pause_frame: false
    sequential_step_sampling: false
    per_device_batch_size: 4
    load_all_data_for_training: true
    resolution_size: 224
    video_resolution_size: 224
    with_state: false
    video_backend: pyav

trainer:
  max_train_steps: 150000
  num_warmup_steps: 5000
  save_interval: 10000
  eval_interval: 1000
  learning_rate:
    base: 1.0e-05
    qwen_vl_interface: 1.0e-05
    action_model: 1.0e-04
  lr_scheduler_type: cosine_with_min_lr
  scheduler_specific_kwargs:
    min_lr: 5.0e-07
  freeze_modules: ''
  loss_scale:
    vla: 1.0
    vlm: 0.1
  max_grad_norm: 1.0
  weight_decay: 0.0
  logging_frequency: 50
  gradient_clipping: 1.0
  gradient_accumulation_steps: 1
  pretrained_checkpoint: /po2/heimrih/VLA-JEPA/checkpoint_1/steps_40000_pytorch_model.pt
  reload_modules: qwen_vl_interface

  optimizer:
    name: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-08
    weight_decay: 1.0e-08

  is_resume: false
  resume_epoch: null
  resume_step: null
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
